### ISSUE TITLE
Error when build for production

### ISSUE THREAD

**Issue by JoseAlbertoVazq** [angular-material-extensions/select-country#26]
**Describe the bug**
When I try to build my Angular project for production, I get the following message: 

"ERROR in ./node_modules/@angular-material-extensions/select-country/fesm5/angular-material-extensions-select-country.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (C:\Users\josea\Documents\Desarrollo\VyooTrip\vyoo-frontend\src\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (C:\Users\josea\Documents\Desarrollo\VyooTrip\vyoo-frontend\src\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (C:\Users\josea\Documents\Desarrollo\VyooTrip\vyoo-frontend\src\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16144:30)
    at Object.forEachChild (C:\Users\josea\Documents\Desarrollo\VyooTrip\vyoo-frontend\src\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16370:24)
    at checkNodeForDecorators (C:\Users\josea\Documents\Desarrollo\VyooTrip\vyoo-frontend\src\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\Users\josea\Documents\Desarrollo\VyooTrip\vyoo-frontend\src\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24)
    at Object.forEachChild (C:\Users\josea\Documents\Desarrollo\VyooTrip\vyoo-frontend\src\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16265:21)
    at checkNodeForDecorators (C:\Users\josea\Documents\Desarrollo\VyooTrip\vyoo-frontend\src\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\Users\josea\Documents\Desarrollo\VyooTrip\vyoo-frontend\src\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24)
    at Object.forEachChild (C:\Users\josea\Documents\Desarrollo\VyooTrip\vyoo-frontend\src\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16322:24)
    at checkNodeForDecorators (C:\Users\josea\Documents\Desarrollo\VyooTrip\vyoo-frontend\src\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\Users\josea\Documents\Desarrollo\VyooTrip\vyoo-frontend\src\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24)
    at Object.forEachChild (C:\Users\josea\Documents\Desarrollo\VyooTrip\vyoo-frontend\src\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16333:24)
    at checkNodeForDecorators (C:\Users\josea\Documents\Desarrollo\VyooTrip\vyoo-frontend\src\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\Users\josea\Documents\Desarrollo\VyooTrip\vyoo-frontend\src\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24)
    at Object.forEachChild (C:\Users\josea\Documents\Desarrollo\VyooTrip\vyoo-frontend\src\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16229:21)"

I tried to upgrade and downgrade a huge list of typescript versions but no one worked for me. This error only happens with this library. I also try the solution of setting the buildOptimizer in angular.json to false and this works, but the amount of data and code that is uploading to server is too much. 

**To Reproduce**
Run ng build --prod

**Expected behavior**
A successfully end when running the production build command.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Firefox Developer Edition

**Additional context**
Maybe if you deleted the one lines comment in the library might the things work?

I'm using the 1.2.0 version because with the followings I get this problem: https://github.com/angular-material-extensions/select-country/issues/25

**Comment by AnthonyNahas** [comment]
duplicate to #22
