### ISSUE TITLE
error when using ng add

### ISSUE THREAD

**Issue by Gsuz** [angular-material-extensions/select-country#5]
ng add @angular-material-extensions/select-country       
Skipping installation: Package already installed
@angular-material-extensions/select-country version =  1.0.0
    ✅️ Added "@angular-material-extensions/select-country" into dependencies
    ✅️ Added "svg-country-flags" into dependencies
    🔍 Installing packages...
    ✅️ "MatSelectCountryModule" is imported
    🚫 Failed to add the icons "@angular-material-extensions/select-country" to assets
⠋ Installing packages.../Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/core/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

TypeError: entry.message.split is not a function
    at MapSubscriber.project (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/core/src/logger/indent.js:34:58)
    at MapSubscriber._next (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Subject.next (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subject.js:60:25)
    at IndentLogger.log (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/core/src/logger/logger.js:76:23)
    at /Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-material-extensions/select-country/schematics/ng-add/index.js:94:28
    at MergeMapSubscriber.project (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/schematics/src/rules/call.js:74:24)
    at MergeMapSubscriber._tryNext (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
    at Observable._trySubscribe (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:30:22)
    at Object.subscribeToResult (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/util/subscribeToResult.js:12:23)
    at MergeMapSubscriber._innerSub (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:82:29)
    at MergeMapSubscriber._tryNext (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:76:14)
    at MergeMapSubscriber._next (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/borkur/Desktop/Forritun/vat-app-affiliate/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:92:26)

**Comment by AnthonyNahas** [comment]
I will check that today

**Comment by Yug0** [comment]
@Gsuz I think that assets are added correctly, just check output path in angular.json.
For example path might be src/assets/svg-country-flags/svg (remove src)

**Comment by Gsuz** [comment]
This install works on a newly created package so I guess there is something off with the project I wass adding this to. Closing this...
